name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:test
    - name: export docker
      run: docker save  my-image-name:test | xz > xz  images.tar.xz
       
    - name: Upload docker image
      uses: actions/upload-artifact@main
      with :
          name: dockerimg
          path:  images.tar.xz
